server:
  port: 9270

spring:
  application:
    name: product-service
#    h2:
#      console:
#        enabled: true
#        settings:
#          web-allow-others: true
#        path: /h2-console
#    datasource:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:tcp://localhost/~/test
#      username: sa
#      password:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kokodo?characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: BITBIT123 #1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
