spring:

  application:
    name: product-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  jpa:
    properties:
      hibernamte:
        format_sql: true
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always
