spring:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/kokodo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    properties:
      hibernamte:
        format_sql: true
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
